config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings
  resources :airportlocs
  resources :flights
  resources :companies
  resources :airports
  root 'flights#home'
   devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

end

app/models/booking.rb
class Booking < ActiveRecord::Base
    belongs_to :user
    
     validates :first_name, length: { minimum: 2 }
    validates :last_name, length: { minimum: 2 }
    validates :first_name, length: { maximum: 10 }
    validates :last_name, length: { maximum: 10 }
    validates_presence_of :country, :gender, :booking_type, :date_of_birth
    validates_uniqueness_of :email, :case_sensitive => false
    validates_format_of :email, :with => /\A([^@\s]+)@((gmail)\.+com)\Z/i, :on => :create,:message =>"must be in @gmail.com"
     validates_format_of :phone_number, with: /\A\d{3}-\d{3}-\d{4}\z/
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.where(user_id: current_user)
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = current_user.bookings.build
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = current_user.bookings.build(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:first_name, :last_name, :gender, :date_of_birth, :country, :phone_number, :email, :booking_type)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<div class="col-md-4">
  </div>
  <div class="col-md-4">
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, placeholder: "Shahad", class:"form-control"  %>
    </div>
  </div>
  <div class="field">
    <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, placeholder: "Yousif", class:"form-control"  %>
    </div>
  </div>
  <div class="field">
    <div class="form-group">
    <%= f.label :gender %><br>
    
    <%= f.select :gender, %w{Male Female}, :prompt => 'Select', required: true, placeholder: 'Gender', class: 'form-control' %>
  </div>
  </div>
  <div class="field">
    <div class="form-group">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth, {:prompt => { :day => 'Select day', :month => 'Select month', :year => 'Select year' }}, {:class => 'date-select'}  %>
    </div>
  </div>
  <div class="field">
    <div class="form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, placeholder: "Iraq", class:"form-control"  %>
    </div>
  </div>
  <div class="field">
    <div class="form-group">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number, placeholder: "111-111-1111", class:"form-control"  %>
    </div>
  </div>
  <div class="field">
    <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, placeholder: "example@gmail.com", class:"form-control"  %>
    </div>
  </div>
  <div class="field">
    <div class="form-group">
    <%= f.label :booking_type %><br>
    <%= f.select :booking_type, %w{Economy Business First_class}, :prompt => 'Select', required: true, placeholder: 'Booking_type', class: 'form-control' %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "create Booking",  class:"btn btn-danger" %>
  </div>
<% end %>
<%= link_to 'Show', @booking, class:"btn btn-default" %> 
<%= link_to 'Back', bookings_path, class:"btn btn-default" %>

</div>
<div class="col-md-4">
  </div>

app/views/bookings/_nave.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="height:1500px">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="dec" class="navbar-brand" href="#"></a>
    </div>
    <ul class="nav navbar-nav">
      <a  class="navbar-brand" href="#"><div class="name1" >ifly </div></a>
      <li><a href="#"><span class="glyphicon glyphicon-home"></span><li class="dec" class="active"><a href="<%= root_path%>"><div class="name" >Home</div></a></li></a></li>

      <li><a href="#"><span class="glyphicon glyphicon-plane"><li><a class="dec" href="<%= flights_path%>"><div class="name" >Flight </div></a></li></a></li>
      <li><a href="#"><span class="glyphicon glyphicon-list-alt"><li><a class="dec" href="<%= bookings_path%>"><div class="name" >Booking</div></a></li></a></li>
      <li><a href="#"><span class="glyphicon glyphicon-map-marker"><li><a class="dec" href="<%= airportlocs_path%>"><div class="name" >Airport Locartion</div></a></li></a></li>
       <li><a href="#"><span class="glyphicon glyphicon-list"></span><li><a class="dec" href="<%= posts_path%>"><div class="name" >Blog</div></a></li></a></li>
       <li><a href="#"><span class="glyphicon glyphicon-user"></span><li><a class="dec" href="<%= admin_root_path%>"><div class="name" >Admin</div></a></li></a></li>
      
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
       <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
     
      
      
    
                             
    </ul>
    
    <br>
    
         <% if user_signed_in? %>
    
    
   <%= link_to 'Edit profile', edit_user_registration_path, class:"btn btn-default"   %> 
   <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"btn btn-default"  %>
   
 <% else %>
 <div class="link">
   <%= link_to "Sign up", new_user_registration_path  %> 
   <%= link_to "Sign in", new_user_session_path %>
 <% end %>
 
  </div>
    <br>
 <ul class="nav navbar-nav navbar-right">
      
    </ul>
</nav>
</div>


</body>
</html>

app/views/bookings/edit.html.erb
<div class="first">
<%= render 'nave'%>
<h1>Editing Booking</h1>

<%= render 'form' %>



</div>

app/views/bookings/index.html.erb
<div class="first">
  <%= render 'nave'%>
<p id="notice"><%= notice %></p>

<h1> Bookings</h1>

<table class="table  table-striped  table-hover table-bordered">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Date of birth</th>
      <th>Country</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Booking type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.first_name %></td>
        <td><%= booking.last_name %></td>
        <td><%= booking.gender %></td>
        <td><%= booking.date_of_birth %></td>
        <td><%= booking.country %></td>
        <td><%= booking.phone_number %></td>
        <td><%= booking.email %></td>
        <td><%= booking.booking_type %></td>
        <td><%= link_to 'Show', booking, class:"btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking), class:"btn btn-default" %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path, class:"btn btn-info" %>
</div>

app/views/bookings/new.html.erb
<div class="first">
<%= render 'nave'%>
<h1>Booking Form</h1>

<%= render 'form' %>




</div>

app/views/bookings/show.html.erb
<div class="first">
  <%= render 'nave'%>
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @booking.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @booking.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @booking.gender %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @booking.date_of_birth %>
</p>

<p>
  <strong>Country:</strong>
  <%= @booking.country %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @booking.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @booking.email %>
</p>

<p>
  <strong>Booking type:</strong>
  <%= @booking.booking_type %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking), class:"btn btn-info" %> 
<%= link_to 'Back', bookings_path , class:"btn btn-info" %>
</div>