config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings
  resources :airportlocs
  resources :flights
  resources :companies
  resources :airports
  root 'flights#home'
   devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :flights
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :date, :price)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name , class:"form-control" %>
  </div>
  </div>
  <div class="field">
    <div class="form-group">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  </div>
  <div class="field">
    <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class:"form-control"  %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit "Create Company",  class:"btn btn-danger" %>
  </div>
<% end %>

app/views/companies/_nave.html.erb
<div class="first">
  <%= render 'nave'%>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="height:1500px">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="dec" class="navbar-brand" href="#"></a>
    </div>
    <ul class="nav navbar-nav">
      <a  class="navbar-brand" href="#"><div class="name1" >ifly </div></a>
      <li><a href="#"><span class="glyphicon glyphicon-home"></span><li class="dec" class="active"><a href="<%= root_path%>"><div class="name" >Home</div></a></li></a></li>

      <li><a href="#"><span class="glyphicon glyphicon-plane"><li><a class="dec" href="<%= flights_path%>"><div class="name" >Flight </div></a></li></a></li>
      <li><a href="#"><span class="glyphicon glyphicon-list-alt"><li><a class="dec" href="<%= bookings_path%>"><div class="name" >Booking</div></a></li></a></li>
      <li><a href="#"><span class="glyphicon glyphicon-map-marker"><li><a class="dec" href="<%= airportlocs_path%>"><div class="name" >Airport Locartion</div></a></li></a></li>
       <li><a href="#"><span class="glyphicon glyphicon-list"></span><li><a class="dec" href="<%= posts_path%>"><div class="name" >Blog</div></a></li></a></li>
       <li><a href="#"><span class="glyphicon glyphicon-user"></span><li><a class="dec" href="<%= admin_root_path%>"><div class="name" >Admin</div></a></li></a></li>
      
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
       <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
     
      
      
    
                             
    </ul>
    
    <br>
    
         <% if user_signed_in? %>
    
    
   <%= link_to 'Edit profile', edit_user_registration_path, class:"btn btn-default"   %> 
   <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"btn btn-default"  %>
   
 <% else %>
 <div class="link">
   <%= link_to "Sign up", new_user_registration_path  %> 
   <%= link_to "Sign in", new_user_session_path %>
 <% end %>
 
  </div>
    <br>
 <ul class="nav navbar-nav navbar-right">
      
    </ul>
</nav>
</div>


</body>
</html>
</div>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company, class:"btn btn-default" %> 
<%= link_to 'Back', companies_path, class:"btn btn-default" %>

app/views/companies/index.html.erb
<div class="first">
<%= render 'nave'%>

<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table class="table  table-striped  table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.date %></td>
        <td><%= company.price %></td>
        <td><%= link_to 'Show', company, class:"btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_company_path(company), class:"btn btn-default" %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path, class:"btn btn-info" %>
</div>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path, class:"btn btn-default" %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @company.date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @company.price %>
</p>

<%= link_to 'Edit', edit_company_path(@company), class:"btn btn-info" %> 
<%= link_to 'Back', companies_path, class:"btn btn-info" %>