config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings
  resources :airportlocs
  resources :flights
  resources :companies
  resources :airports
  root 'flights#home'
   devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

end

app/models/airport.rb
class Airport < ActiveRecord::Base
     has_many :flights, class_name: "Flight", foreign_key: "from_airport_id"
     has_many :flights, class_name: "Flight", foreign_key: "to_airport_id"
    
     def full_airport_name
        "#{city} #{code}"
     end
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: [:show, :edit, :update, :destroy]

  # GET /airports
  # GET /airports.json
  def index
    @airports = Airport.all
  end

  # GET /airports/1
  # GET /airports/1.json
  def show
  end

  # GET /airports/new
  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports
  # POST /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: 'Airport was successfully created.' }
        format.json { render :show, status: :created, location: @airport }
      else
        format.html { render :new }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1
  # PATCH/PUT /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: 'Airport was successfully updated.' }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.json
  def destroy
    @airport.destroy
    respond_to do |format|
      format.html { redirect_to airports_url, notice: 'Airport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airport_params
      params.require(:airport).permit(:city, :code)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_form.html.erb
<%= form_for(@airport) do |f| %>
  <% if @airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
      <% @airport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class:"form-control"  %>
    </div>
  </div>
  <div class="field">
    <div class="form-group">
    <%= f.label :code %><br>
    <%= f.text_field :code, class:"form-control"  %>
    </div>
  </div>
  <div class="actions" >
    <%= f.submit "create Airport",  class:"btn btn-danger" %>
  </div>
<% end %>

app/views/airports/_nave.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="height:1500px">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="dec" class="navbar-brand" href="#"></a>
    </div>
    <ul class="nav navbar-nav">
      <a  class="navbar-brand" href="#"><div class="name1" >ifly </div></a>
      <li><a href="#"><span class="glyphicon glyphicon-home"></span><li class="dec" class="active"><a href="<%= root_path%>"><div class="name" >Home</div></a></li></a></li>

      <li><a href="#"><span class="glyphicon glyphicon-plane"><li><a class="dec" href="<%= flights_path%>"><div class="name" >Flight </div></a></li></a></li>
      <li><a href="#"><span class="glyphicon glyphicon-list-alt"><li><a class="dec" href="<%= bookings_path%>"><div class="name" >Booking</div></a></li></a></li>
      <li><a href="#"><span class="glyphicon glyphicon-map-marker"><li><a class="dec" href="<%= airportlocs_path%>"><div class="name" >Airport Locartion</div></a></li></a></li>
      
       <li><a href="#"><span class="glyphicon glyphicon-user"></span><li><a class="dec" href="<%= admin_root_path%>"><div class="name" >Admin</div></a></li></a></li>
      
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
       <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
     
      
      
    
                             
    </ul>
    
    <br>
    
         <% if user_signed_in? %>
    
    
   <%= link_to 'Edit profile', edit_user_registration_path, class:"btn btn-default"   %> 
   <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"btn btn-default"  %>
   
 <% else %>
 <div class="link">
   <%= link_to "Sign up", new_user_registration_path  %> 
   <%= link_to "Sign in", new_user_session_path %>
 <% end %>
 
  </div>
    <br>
 <ul class="nav navbar-nav navbar-right">
      
    </ul>
</nav>
</div>


</body>
</html>

app/views/airports/edit.html.erb
<h1>Editing Airport</h1>

<%= render 'form' %>

<%= link_to 'Show', @airport , class:"btn btn-default"%> 
<%= link_to 'Back', airports_path , class:"btn btn-default"%>

app/views/airports/index.html.erb
<div class="first">
   <%= render 'nave'%>
    <p id="notice"><%= notice %></p>
    
    <h1>Listing Airports</h1>
    
    <table class="table  table-striped  table-hover table-bordered">
      <thead>
        <tr>
          <th>City</th>
          <th>Code</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @airports.each do |airport| %>
          <tr>
            <td><%= airport.city %></td>
            <td><%= airport.code %></td>
            <td><%= link_to 'Show', airport, class:"btn btn-default" %></td>
            <td><%= link_to 'Edit', edit_airport_path(airport), class:"btn btn-default" %></td>
            <td><%= link_to 'Destroy', airport, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <br>
    
    <%= link_to 'New Airport', new_airport_path, class:"btn btn-info" %>

app/views/airports/new.html.erb
<h1>New Airport</h1>

<%= render 'form' %>

<%= link_to 'Back', airports_path, class:"btn btn-default" %>

app/views/airports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @airport.city %>
</p>

<p>
  <strong>Code:</strong>
  <%= @airport.code %>
</p>

<%= link_to 'Edit', edit_airport_path(@airport), class:"btn btn-info" %> 
<%= link_to 'Back', airports_path , class:"btn btn-info"%>